trigger: none

parameters:
- name: env
  displayName: Environment
  type: string
  default: dev
  values:
  - dev
  - tst
  - prd
- name: terraformCmd
  displayName: Terraform Command
  type: string
  default: plan
  values:
  - plan
  - apply
  - destroy

extends:
  template: terraform.yaml
  parameters:
    env: ${{ parameters.env }}
    terraformCmd: ${{ parameters.terraformCmd }}